/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrendsRouteImport } from './routes/app.trends'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppCompetitorsRouteImport } from './routes/app.competitors'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/trends': typeof AppTrendsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/competitors'
    | '/app/insights'
    | '/app/performance'
    | '/app/trends'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/competitors'
    | '/app/insights'
    | '/app/performance'
    | '/app/trends'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/competitors'
    | '/app/insights'
    | '/app/performance'
    | '/app/trends'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trends': {
      id: '/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
