/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrendsRouteImport } from './routes/app.trends'
import { Route as AppTodosRouteImport } from './routes/app.todos'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppOutcomesRouteImport } from './routes/app.outcomes'
import { Route as AppMovesRouteImport } from './routes/app.moves'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppIdeasRouteImport } from './routes/app.ideas'
import { Route as AppDynamicsRouteImport } from './routes/app.dynamics'
import { Route as AppCompetitorsRouteImport } from './routes/app.competitors'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppTodosRoute = AppTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppOutcomesRoute = AppOutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => AppRoute,
} as any)
const AppMovesRoute = AppMovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasRoute = AppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppDynamicsRoute = AppDynamicsRouteImport.update({
  id: '/dynamics',
  path: '/dynamics',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/auth': typeof AuthRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/moves': typeof AppMovesRoute
  '/app/outcomes': typeof AppOutcomesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/todos': typeof AppTodosRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth': typeof AuthRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/moves': typeof AppMovesRoute
  '/app/outcomes': typeof AppOutcomesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/todos': typeof AppTodosRoute
  '/app/trends': typeof AppTrendsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/auth': typeof AuthRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/moves': typeof AppMovesRoute
  '/app/outcomes': typeof AppOutcomesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/todos': typeof AppTodosRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/auth'
    | '/app/competitors'
    | '/app/dynamics'
    | '/app/ideas'
    | '/app/insights'
    | '/app/moves'
    | '/app/outcomes'
    | '/app/performance'
    | '/app/settings'
    | '/app/todos'
    | '/app/trends'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/auth'
    | '/app/competitors'
    | '/app/dynamics'
    | '/app/ideas'
    | '/app/insights'
    | '/app/moves'
    | '/app/outcomes'
    | '/app/performance'
    | '/app/settings'
    | '/app/todos'
    | '/app/trends'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/auth'
    | '/app/competitors'
    | '/app/dynamics'
    | '/app/ideas'
    | '/app/insights'
    | '/app/moves'
    | '/app/outcomes'
    | '/app/performance'
    | '/app/settings'
    | '/app/todos'
    | '/app/trends'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trends': {
      id: '/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/todos': {
      id: '/app/todos'
      path: '/todos'
      fullPath: '/app/todos'
      preLoaderRoute: typeof AppTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outcomes': {
      id: '/app/outcomes'
      path: '/outcomes'
      fullPath: '/app/outcomes'
      preLoaderRoute: typeof AppOutcomesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/moves': {
      id: '/app/moves'
      path: '/moves'
      fullPath: '/app/moves'
      preLoaderRoute: typeof AppMovesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ideas': {
      id: '/app/ideas'
      path: '/ideas'
      fullPath: '/app/ideas'
      preLoaderRoute: typeof AppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dynamics': {
      id: '/app/dynamics'
      path: '/dynamics'
      fullPath: '/app/dynamics'
      preLoaderRoute: typeof AppDynamicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppDynamicsRoute: typeof AppDynamicsRoute
  AppIdeasRoute: typeof AppIdeasRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMovesRoute: typeof AppMovesRoute
  AppOutcomesRoute: typeof AppOutcomesRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodosRoute: typeof AppTodosRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppDynamicsRoute: AppDynamicsRoute,
  AppIdeasRoute: AppIdeasRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMovesRoute: AppMovesRoute,
  AppOutcomesRoute: AppOutcomesRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodosRoute: AppTodosRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
